### ISSUE TITLE
Exemple?

### ISSUE THREAD

**Issue by dagatsoin** [netanelgilad/meteor-angular-file-upload#4]
Hello,

I am new to Meteor and Angular. I am looking for a simple exemple to use this package.
For nom my template and my controller are OK.

I understand how it works with PHP but not with Meteor.

What url to use ?
What to do on server side ? I imagine a Meteor.call() but I don't know when to call it and how I could use the callbacks.

**Comment by netanelgilad** [comment]
Hey @dagatsoin,
This package gives you a nice angular file upload package for the client side only.
But in order to have real file uploads with meteor you need a server side package as well like CollectionFS or FileCollection.
Hopefully you know the tutorial at http://angularjs.meteor.com. Since you asked (and a few others I encountered that need this) I'll write a chapter in the tutorial about file uploads. Hopefully I'll get to it in the next few days.
Keep an eye on this thread and i'll update it here.

**Comment by MilosStanic** [comment]
+1 for file upload example for angular-meteor

**Comment by gpothier** [comment]
Hi @netanelgilad, it seems you haven't had time to create a tutorial chapter yet, but in the mean time could you please just share a piece of working code? Or maybe you have a project somewhere on github that uses the uploader that we could see? I can't get the dependencies right in the client.

**Comment by Xample** [comment]
+1 for an example, even 10 lines would be helpful understanding how to mix the angular code

**Comment by netanelgilad** [comment]
Hey guys,
Sorry I'm not getting to this, too busy. But it is on my todo list.
Just to get you guys going with CollectionFS file uploads, here is a small example: https://github.com/netanelgilad/angular-meteor-collectionfs-example.
It doesn't use this library, cause with CollectionFS it is so easy it just seems unnecessary :)

**Comment by adriangordon1231** [comment]
Basically unusable without a code example.

**Comment by dagatsoin** [comment]
way to old
